- name: "Installing additional spackages"
  package: pkg={{ item }} state=installed
  with_items:
  - git
  - vim
  - tree
  - man
  - i2c-tools
  - minicom
  - screen

- name: "Install the meld rpm from a remote repo"
  yum:
    name: http://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/m/meld-3.16.4-2.el7.noarch.rpm
    state: present

- name: set X11UseLocalhost no in sshd_config
  lineinfile: dest=/etc/ssh/sshd_config regexp="X11UseLocalhost "
    line="X11UseLocalhost no"

- name: "Install gotop monitoring tool"
  git:
    repo: 'https://github.com/cjbassi/gotop.git'
    dest: /tmp/gotop

- name: "Download gotop binary to /root"
  shell: /tmp/gotop/scripts/download.sh
  args:
    creates: /root/gotop
  notify: [ 'Copy gotop' ]

