- name: "Installing additional spackages"
  package: pkg={{ item }} state=installed
  with_items:
  - git
  - vim
  - tree
  - man
  - i2c-tools
  - minicom
  - screen
  - python-devel

- name: "Install the meld rpm from a remote repo"
  yum:
    name: http://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/m/meld-3.16.4-2.el7.noarch.rpm
    state: present

- name: set X11UseLocalhost no in sshd_config
  lineinfile: dest=/etc/ssh/sshd_config regexp="X11UseLocalhost "
    line="X11UseLocalhost no"

- name: "GIT clone gotop monitoring tool"
  git:
    repo: 'https://github.com/cjbassi/gotop.git'
    dest: /root/toolsrc/gotop

- name: "Download gotop binary to /root"
  shell: /root/toolsrc/gotop/scripts/download.sh
  args:
    creates: /root/gotop
  notify: [ 'Copy gotop' ]

- name: "Install psutil with pip"
  pip:
    name: psutil

- name: "Install glances with pip"
  pip:
    name: glances

- name: "GIT clone linux-serial-test tool"
  git:
    repo: 'https://github.com/MEN-Mikro-Elektronik/linux-serial-test.git'
    dest: /root/toolsrc/linux-serial-test

- name: "Compile linux-serial-test tool"
  shell: gcc linux-serial-test.c -o /usr/bin/linux-serial-test
  args:
    chdir: /root/toolsrc/linux-serial-test
    creates: /usr/bin/linux-serial-test

